name: Go Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  call-go-tests:
    uses: eclipse-xfsc/dev-ops/.github/workflows/go-test.yml@main
    with:
      go-version: '1.24'
